<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5LyB5Lia572R56uZ');
$cfg_Cs[3]=array(0,1,1,'6K665Z2b6Zeo5oi3');
$cfg_Cs[4]=array(0,1,1,'5ZWG5Z+O572R56uZ');
$cfg_Cs[5]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[6]=array(5,1,1,'572R56uZ5bu66K6+');
$cfg_Cs[7]=array(5,1,1,'5o+S5Lu25byA5Y+R');
$cfg_Cs[8]=array(5,1,1,'572R56uZ5LyY5YyW');
?>